# Generated by Django 5.1.3 on 2024-11-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32, unique=True)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mark')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('millage', models.FloatField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('volume', models.FloatField()),
                ('have', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='vid/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carmodel')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mark')),
            ],
        ),
    ]
